### ISSUE TITLE
Add InjectAsync to allow custom parameter decorators which are async

### ISSUE THREAD

**Issue by Xetatronics** [swimlane/trafficlight#20]
I have some custom decorators to validate my parameters. Currently, i can create them with Inject(), and that works fine. However, i would like to use promises inside my decorators but trafficlight is not waiting for the execution.

My proposal is to add InjectAsync(). I can do this and would like to push a PR, but first i want to be sure someone is here to approve my request. Please let me know!

Other than that - Thanks for this package, i use it because no similar package can deal with custom routers.

**Comment by shaunburdick** [comment]
Go ahead and create a PR and I'll take a look. Maybe instead of the new function we can just add the await and bump the version number. (In theory it should be backwards compatible unless someone is purposely expecting a promise back?)

I'll be honest though, we've moved away from this internally so there is probably little life left in this library. Chances are this would be the last change before we archive the repository. ☹️

**Comment by Xetatronics** [comment]
Hey Shaun, 
At first I was also thinking of simple adding await, but decided against it because most (all shipped with the package) decorators are not requiring promisses, so awaiting these functions would just create useless promisses executing a non-promise function, which just increases the callstack  where it's not nessessary.

Oh no, thats bad news :( Please wait for my PR next week, so i can still have this. I dont get why there is no other package which supports custom routers like koa-tree-router. This makes trafficlight so different and important for me. If it would help you, i could take maintanance or ownership of trafficlight. I have no plans to further extend this package atm because it just works good, but as i'm using it I might find improvements for it.

Utimately this leads me to the question if you have any concerns against this package and if you would advice me against it for a production environment, because of security or something? 

Have a nice weekend!

**Comment by Xetatronics** [comment]
I added my PR: https://github.com/swimlane/trafficlight/pull/21

**Comment by shaunburdick** [comment]
> Utimately this leads me to the question if you have any concerns against this package and if you would advice me against it for a production environment, because of security or something?
I don't have any security concerns at this point. It's a perfectly fine library we used for a while internally. We transitioned our APIs to a different framework so this library was no longer in use. 

It won't be going away, we just will not be developing it any further.
Thanks for the PR, I'll take a look at it today. 👍

**Comment by Xetatronics** [comment]
Thanks a lot for merging my PR and releasing a new version! I just updated and it works perfectly, so issue can be closed :)

**Comment by Xetatronics** [comment]
Quickly reopened for a question: Is there a reason why tslint-config-security Is no dev dependency? Just wondering

**Comment by shaunburdick** [comment]
No reason, just a mistake

**Comment by shaunburdick** [comment]
Fixed.

**Comment by Xetatronics** [comment]
Thanks!
