### ISSUE TITLE
Need more explanation

### ISSUE THREAD

**Issue by BruceHem** [swimlane/trafficlight#8]
I'm not clear with the following snippet.

```
// if you are using with some sort of DI system you can pass
// a third parameter callback to get the instance vs new ctrl.
// bindRoutes(routerRoutes, [ProfileController], (ctrl) => injector.get(ctrl));

```

Is there a better example?

**Comment by amcdnl** [comment]
Absolutely. DI systems typically require you to use their resolution system, in this example I'm using `injection-js`'s `get` function to resolve the instance of the controller. If this isn't provided, it just does `new controller` internally.

Does that answer your question?
